android.useAndroidX=true

android.bundle.compression.enabled=true
android.bundle.abi.enableSplit=true
android.bundle.language.enableSplit=true
android.bundle.density.enableSplit=true

# R8 en modo completo (ya activo por defecto en AGP 8+)
android.enableR8.fullMode=true

# Aumentar memoria y habilitar caché
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.caching=true
org.gradle.parallel=true